# Generated by Django 3.0.3 on 2020-05-01 01:58

import cloudApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous user', max_length=30)),
                ('account', models.TextField()),
                ('password', models.TextField()),
                ('usertype', models.CharField(default='common', max_length=20)),
            ],
            options={
                'db_table': 'CloudUser',
            },
            managers=[
                ('CUser', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CloudStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('filetype', models.TextField()),
                ('file', models.FileField(upload_to=cloudApp.models.upload_place)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudApp.CloudUser')),
            ],
            options={
                'db_table': 'CloudStorage',
            },
            managers=[
                ('CStorage', django.db.models.manager.Manager()),
            ],
        ),
    ]
