# Generated by Django 3.0.3 on 2020-05-01 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous user', max_length=30)),
                ('account', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('usertype', models.CharField(default='common', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'CloudUser',
            },
            managers=[
                ('CUser', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CloudStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('filetype', models.TextField()),
                ('file', models.FileField(upload_to='E:\\GitHub_Web\\IMISCloud\\IMISCloud\\CloudStorage/')),
                ('attribute', models.TextField(default='private')),
                ('status', models.CharField(default='saved', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudApp.CloudUser')),
            ],
            options={
                'db_table': 'CloudStorage',
            },
            managers=[
                ('CStorage', django.db.models.manager.Manager()),
            ],
        ),
    ]
