# Generated by Django 3.0.3 on 2020-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudApp', '0002_cloudstorage_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduser',
            name='account',
            field=models.TextField(unique=True),
        ),
    ]
